backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "_site/assets/images/uploads"
public_folder: "/assets/images/uploads" 

collections:
  - name: "artists"
    label: "Artists"
    folder: "artists"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/artist.njk" }
      - { label: "Artist", name: "artist", widget: "string", required: true }
      - { label: "CV", name: "cv", widget: "file", required: false }
      - { label: "Featured Image", name: "featuredImage", widget: "markdown", required: true }
      - { label: "Gallery", name: "gallery", widget: "markdown", required: false }